import { CatalogResponse, CoffeeBar } from '../types/catalog';

export const INITIAL_BARS: CoffeeBar[] = [
  { id: 1, name: 'Кофейня №1 (Центр)', address: 'ул. Тверская, 12', telegram_chat_id: -1001928374, is_active: true },
  { id: 2, name: 'Кофейня №2 (Арбат)', address: 'ул. Новый Арбат, 28', telegram_chat_id: -1001928375, is_active: true },
  { id: 3, name: 'Кофейня №3 (Сити)', address: 'Пресненская наб., 8 стр. 1', telegram_chat_id: -1001928376, is_active: true },
  { id: 4, name: 'Кофейня №4 (Флакон)', address: 'ул. Большая Новодмитровская, 36', telegram_chat_id: -1001928377, is_active: true },
  { id: 5, name: 'Кофейня №5 (Покровка)', address: 'ул. Покровка, 17', telegram_chat_id: -1001928378, is_active: true },
];

export const MOCK_CATALOG_DATA: CatalogResponse = {
  total_categories: 8,
  total_products: 225,
  categories: [
    {
      category: 'Стаканы и крышки',
      items_count: 14,
      items: [
        { id: 1, sku: 'SKU-0001', name: 'Стакан бумажный однослойный 100 мл', category: 'Стаканы и крышки', unit: 'уп (50 шт)', available_qty: 45, is_stop: false },
        { id: 2, sku: 'SKU-0002', name: 'Стакан бумажный двухслойный Крафт 200 мл', category: 'Стаканы и крышки', unit: 'уп (40 шт)', available_qty: 60, is_stop: false },
        { id: 3, sku: 'SKU-0003', name: 'Стакан бумажный двухслойный Крафт 300 мл', category: 'Стаканы и крышки', unit: 'уп (35 шт)', available_qty: 12, is_stop: false },
        { id: 4, sku: 'SKU-0004', name: 'Стакан бумажный двухслойный Крафт 400 мл', category: 'Стаканы и крышки', unit: 'уп (30 шт)', available_qty: 0, is_stop: true },
        { id: 5, sku: 'SKU-0005', name: 'Стакан бумажный двухслойный Черный 300 мл', category: 'Стаканы и крышки', unit: 'уп (35 шт)', available_qty: 25, is_stop: false },
        { id: 6, sku: 'SKU-0006', name: 'Стакан бумажный двухслойный Черный 400 мл', category: 'Стаканы и крышки', unit: 'уп (30 шт)', available_qty: 18, is_stop: false },
        { id: 7, sku: 'SKU-0007', name: 'Стакан прозрачный ПЭТ для айс-кофе 400 мл', category: 'Стаканы и крышки', unit: 'уп (50 шт)', available_qty: 30, is_stop: false },
        { id: 8, sku: 'SKU-0008', name: 'Стакан прозрачный ПЭТ для айс-кофе 500 мл', category: 'Стаканы и крышки', unit: 'уп (50 шт)', available_qty: 8, is_stop: false },
        { id: 9, sku: 'SKU-0009', name: 'Крышка пластиковая с питейником d80 черная', category: 'Стаканы и крышки', unit: 'уп (100 шт)', available_qty: 80, is_stop: false },
        { id: 10, sku: 'SKU-0010', name: 'Крышка пластиковая с питейником d90 черная', category: 'Стаканы и крышки', unit: 'уп (100 шт)', available_qty: 75, is_stop: false },
        { id: 11, sku: 'SKU-0011', name: 'Крышка купольная без отверстия d90 (для шейков)', category: 'Стаканы и крышки', unit: 'уп (100 шт)', available_qty: 20, is_stop: false },
        { id: 12, sku: 'SKU-0012', name: 'Крышка купольная с отверстием d90', category: 'Стаканы и крышки', unit: 'уп (100 шт)', available_qty: 0, is_stop: true },
        { id: 13, sku: 'SKU-0013', name: 'Капхолдер картонный гофрированный 300/400 мл', category: 'Стаканы и крышки', unit: 'уп (100 шт)', available_qty: 50, is_stop: false },
        { id: 14, sku: 'SKU-0014', name: 'Подстаканник из формованного волокна на 2 стакана', category: 'Стаканы и крышки', unit: 'уп (50 шт)', available_qty: 34, is_stop: false },
      ]
    },
    {
      category: 'Кофе, Чай, Дрипы',
      items_count: 17,
      items: [
        { id: 15, sku: 'SKU-0015', name: 'Кофе в зернах House Blend 80/20 (1 кг)', category: 'Кофе, Чай, Дрипы', unit: 'кг', available_qty: 40, is_stop: false },
        { id: 16, sku: 'SKU-0016', name: 'Кофе в зернах 100% Арабика Бразилия Серрадо (1 кг)', category: 'Кофе, Чай, Дрипы', unit: 'кг', available_qty: 30, is_stop: false },
        { id: 17, sku: 'SKU-0017', name: 'Кофе в зернах Эфиопия Иргачефф мытая (1 кг)', category: 'Кофе, Чай, Дрипы', unit: 'кг', available_qty: 15, is_stop: false },
        { id: 18, sku: 'SKU-0018', name: 'Кофе в зернах Колумбия Супремо (1 кг)', category: 'Кофе, Чай, Дрипы', unit: 'кг', available_qty: 20, is_stop: false },
        { id: 19, sku: 'SKU-0019', name: 'Кофе в зернах Декаф (без кофеина, 1 кг)', category: 'Кофе, Чай, Дрипы', unit: 'кг', available_qty: 5, is_stop: false },
        { id: 20, sku: 'SKU-0020', name: 'Дрип-пакеты Бразилия Сантос (бокс 10 шт)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 24, is_stop: false },
        { id: 21, sku: 'SKU-0021', name: 'Дрип-пакеты Эфиопия Гуджи (бокс 10 шт)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 0, is_stop: true },
        { id: 22, sku: 'SKU-0022', name: 'Дрип-пакеты Гондурас Сан Маркос (бокс 10 шт)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 16, is_stop: false },
        { id: 23, sku: 'SKU-0023', name: 'Дрип-пакеты Кения АА (бокс 10 шт)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 12, is_stop: false },
        { id: 24, sku: 'SKU-0024', name: 'Чай листовой черный Ассам Мокалбари (500 г)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 18, is_stop: false },
        { id: 25, sku: 'SKU-0025', name: 'Чай листовой черный Эрл Грей с бергамотом (500 г)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 14, is_stop: false },
        { id: 26, sku: 'SKU-0026', name: 'Чай листовой зеленый Сенча премиум (500 г)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 15, is_stop: false },
        { id: 27, sku: 'SKU-0027', name: 'Чай листовой зеленый с жасмином (500 г)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 9, is_stop: false },
        { id: 28, sku: 'SKU-0028', name: 'Чай травяной Альпийский луг (500 г)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 11, is_stop: false },
        { id: 29, sku: 'SKU-0029', name: 'Чай фруктовый Наглый Фрукт (500 г)', category: 'Кофе, Чай, Дрипы', unit: 'уп', available_qty: 13, is_stop: false },
        { id: 30, sku: 'SKU-0030', name: 'Матча церемониальная Uji Grade A (100 г)', category: 'Кофе, Чай, Дрипы', unit: 'бан', available_qty: 7, is_stop: false },
        { id: 31, sku: 'SKU-0031', name: 'Какао-порошок алкализованный Extra Brute (1 кг)', category: 'Кофе, Чай, Дрипы', unit: 'кг', available_qty: 22, is_stop: false },
      ]
    },
    {
      category: 'Сиропы',
      items_count: 16,
      items: [
        { id: 32, sku: 'SKU-0032', name: 'Сироп Карамель (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 28, is_stop: false },
        { id: 33, sku: 'SKU-0033', name: 'Сироп Соленая карамель (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 35, is_stop: false },
        { id: 34, sku: 'SKU-0034', name: 'Сироп Ваниль Мадагаскар (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 22, is_stop: false },
        { id: 35, sku: 'SKU-0035', name: 'Сироп Лесной орех / Фундук (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 19, is_stop: false },
        { id: 36, sku: 'SKU-0036', name: 'Сироп Кокос (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 14, is_stop: false },
        { id: 37, sku: 'SKU-0037', name: 'Сироп Лаванда Прованс (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 8, is_stop: false },
        { id: 38, sku: 'SKU-0038', name: 'Сироп Мята перечная (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 12, is_stop: false },
        { id: 39, sku: 'SKU-0039', name: 'Сироп Малина (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 0, is_stop: true },
        { id: 40, sku: 'SKU-0040', name: 'Сироп Манго-Маракуйя (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 17, is_stop: false },
        { id: 41, sku: 'SKU-0041', name: 'Сироп Клен Канадский (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 10, is_stop: false },
        { id: 42, sku: 'SKU-0042', name: 'Сироп Тыквенный пряный (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 6, is_stop: false },
        { id: 43, sku: 'SKU-0043', name: 'Сироп Имбирный пряник (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 15, is_stop: false },
        { id: 44, sku: 'SKU-0044', name: 'Сироп Попкорн (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 9, is_stop: false },
        { id: 45, sku: 'SKU-0045', name: 'Сироп Фисташка (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 0, is_stop: true },
        { id: 46, sku: 'SKU-0046', name: 'Сироп Блю Кюрасао (1 л)', category: 'Сиропы', unit: 'бут', available_qty: 14, is_stop: false },
        { id: 47, sku: 'SKU-0047', name: 'Дозатор помповый для бутылки сиропа 1 л', category: 'Сиропы', unit: 'шт', available_qty: 25, is_stop: false },
      ]
    },
    {
      category: 'Основы и порошки',
      items_count: 15,
      items: [
        { id: 48, sku: 'SKU-0048', name: 'Пюре фруктовое Манго Альфонсо (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 16, is_stop: false },
        { id: 49, sku: 'SKU-0049', name: 'Пюре фруктовое Малина натуральная (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 12, is_stop: false },
        { id: 50, sku: 'SKU-0050', name: 'Пюре фруктовое Клубника сладкая (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 20, is_stop: false },
        { id: 51, sku: 'SKU-0051', name: 'Пюре фруктовое Облепиха пряная (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 8, is_stop: false },
        { id: 52, sku: 'SKU-0052', name: 'Смесь-порошок для Фраппе Ваниль (1 кг)', category: 'Основы и порошки', unit: 'уп', available_qty: 10, is_stop: false },
        { id: 53, sku: 'SKU-0053', name: 'Смесь для сырной/сливочной пенки Cheese Foam (1 кг)', category: 'Основы и порошки', unit: 'уп', available_qty: 6, is_stop: false },
        { id: 54, sku: 'SKU-0054', name: 'Шоколад горячий темный 60% порошок (1 кг)', category: 'Основы и порошки', unit: 'кг', available_qty: 14, is_stop: false },
        { id: 55, sku: 'SKU-0055', name: 'Корица молотая цейлонская премиум (250 г)', category: 'Основы и порошки', unit: 'бан', available_qty: 30, is_stop: false },
        { id: 56, sku: 'SKU-0056', name: 'Мускатный орех молотый (150 г)', category: 'Основы и порошки', unit: 'бан', available_qty: 15, is_stop: false },
        { id: 57, sku: 'SKU-0057', name: 'Сахар порционный белые стики 5 г (бокс 1000 шт)', category: 'Основы и порошки', unit: 'уп', available_qty: 18, is_stop: false },
        { id: 58, sku: 'SKU-0058', name: 'Сахар тростниковый стики 5 г (бокс 1000 шт)', category: 'Основы и порошки', unit: 'уп', available_qty: 12, is_stop: false },
        { id: 59, sku: 'SKU-0059', name: 'Сахарозаменитель ФитПарад №7 (пакет 200 стиков)', category: 'Основы и порошки', unit: 'уп', available_qty: 0, is_stop: true },
        { id: 60, sku: 'SKU-0060', name: 'Топинг Шоколадный десертный (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 22, is_stop: false },
        { id: 61, sku: 'SKU-0061', name: 'Топинг Карамельный с морской солью (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 19, is_stop: false },
        { id: 62, sku: 'SKU-0062', name: 'Молоко сгущенное цельное ГОСТ (1 кг)', category: 'Основы и порошки', unit: 'бут', available_qty: 25, is_stop: false },
      ]
    },
    {
      category: 'Молоко и напитки',
      items_count: 14,
      items: [
        { id: 63, sku: 'SKU-0063', name: 'Молоко пастеризованное 3.2% Barista (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 120, is_stop: false },
        { id: 64, sku: 'SKU-0064', name: 'Молоко безлактозное 3.2% (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 45, is_stop: false },
        { id: 65, sku: 'SKU-0065', name: 'Растительное молоко Овсяное Barista (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 85, is_stop: false },
        { id: 66, sku: 'SKU-0066', name: 'Растительное молоко Кокосовое Barista (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 60, is_stop: false },
        { id: 67, sku: 'SKU-0067', name: 'Растительное молоко Миндальное Barista (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 50, is_stop: false },
        { id: 68, sku: 'SKU-0068', name: 'Растительное молоко Банановое Barista (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 30, is_stop: false },
        { id: 69, sku: 'SKU-0069', name: 'Растительное молоко Фундучное Barista (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 0, is_stop: true },
        { id: 70, sku: 'SKU-0070', name: 'Сливки питьевые 10% (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 40, is_stop: false },
        { id: 71, sku: 'SKU-0071', name: 'Сливки кондитерские 33% для взбивания (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 25, is_stop: false },
        { id: 72, sku: 'SKU-0072', name: 'Сок Rich Апельсин 100% (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 24, is_stop: false },
        { id: 73, sku: 'SKU-0073', name: 'Сок Rich Яблоко осветленный (1 л)', category: 'Молоко и напитки', unit: 'шт', available_qty: 20, is_stop: false },
        { id: 74, sku: 'SKU-0074', name: 'Тоник индийский классический (0.33 л, стекл)', category: 'Молоко и напитки', unit: 'бут', available_qty: 48, is_stop: false },
        { id: 75, sku: 'SKU-0075', name: 'Вода артезианская негазированная (0.5 л)', category: 'Молоко и напитки', unit: 'бут', available_qty: 96, is_stop: false },
        { id: 76, sku: 'SKU-0076', name: 'Вода артезианская газированная (0.5 л)', category: 'Молоко и напитки', unit: 'бут', available_qty: 48, is_stop: false },
      ]
    },
    {
      category: 'Десерты и выпечка',
      items_count: 14,
      items: [
        { id: 77, sku: 'SKU-0077', name: 'Круассан классический на сливочном масле', category: 'Десерты и выпечка', unit: 'уп (10 шт)', available_qty: 15, is_stop: false },
        { id: 78, sku: 'SKU-0078', name: 'Круассан миндальный с франжипаном', category: 'Десерты и выпечка', unit: 'уп (8 шт)', available_qty: 8, is_stop: false },
        { id: 79, sku: 'SKU-0079', name: 'Круассан Шоколадный (Пан-о-шоколя)', category: 'Десерты и выпечка', unit: 'уп (10 шт)', available_qty: 12, is_stop: false },
        { id: 80, sku: 'SKU-0080', name: 'Улитка с изюмом и заварным кремом', category: 'Десерты и выпечка', unit: 'уп (8 шт)', available_qty: 7, is_stop: false },
        { id: 81, sku: 'SKU-0081', name: 'Даниш с малиной и ванильным кремом', category: 'Десерты и выпечка', unit: 'уп (8 шт)', available_qty: 0, is_stop: true },
        { id: 82, sku: 'SKU-0082', name: 'Чизкейк Нью-Йорк порционный заморозка', category: 'Десерты и выпечка', unit: 'уп (12 порц)', available_qty: 10, is_stop: false },
        { id: 83, sku: 'SKU-0083', name: 'Чизкейк Сан-Себастьян с карамельным топингом', category: 'Десерты и выпечка', unit: 'уп (10 порц)', available_qty: 6, is_stop: false },
        { id: 84, sku: 'SKU-0084', name: 'Эклер Ванильный кракелин', category: 'Десерты и выпечка', unit: 'уп (6 шт)', available_qty: 14, is_stop: false },
        { id: 85, sku: 'SKU-0085', name: 'Эклер Соленая карамель и пекан', category: 'Десерты и выпечка', unit: 'уп (6 шт)', available_qty: 9, is_stop: false },
        { id: 86, sku: 'SKU-0086', name: 'Брауни шоколадный с грецким орехом', category: 'Десерты и выпечка', unit: 'уп (12 шт)', available_qty: 16, is_stop: false },
        { id: 87, sku: 'SKU-0087', name: 'Кукис Американский с шоколадными дропсами', category: 'Десерты и выпечка', unit: 'уп (15 шт)', available_qty: 18, is_stop: false },
        { id: 88, sku: 'SKU-0088', name: 'Макаронс Ассорти 5 вкусов', category: 'Десерты и выпечка', unit: 'уп (20 шт)', available_qty: 11, is_stop: false },
        { id: 89, sku: 'SKU-0089', name: 'Сырники из фермерского творога 9%', category: 'Десерты и выпечка', unit: 'уп (20 шт)', available_qty: 14, is_stop: false },
        { id: 90, sku: 'SKU-0090', name: 'Сэндвич с индейкой и соусом песто (готовый)', category: 'Десерты и выпечка', unit: 'шт', available_qty: 0, is_stop: true },
      ]
    },
    {
      category: 'Расходники и упаковка',
      items_count: 14,
      items: [
        { id: 91, sku: 'SKU-0091', name: 'Трубочки бумажные крафт d6 мм (длина 20 см)', category: 'Расходники и упаковка', unit: 'уп (250 шт)', available_qty: 35, is_stop: false },
        { id: 92, sku: 'SKU-0092', name: 'Трубочки биоразлагаемые черные d8 мм (для шейков)', category: 'Расходники и упаковка', unit: 'уп (200 шт)', available_qty: 28, is_stop: false },
        { id: 93, sku: 'SKU-0093', name: 'Салфетки барные белые 24х24 см', category: 'Расходники и упаковка', unit: 'уп (500 шт)', available_qty: 45, is_stop: false },
        { id: 94, sku: 'SKU-0094', name: 'Салфетки крафт эко в диспенсер 20х20 см', category: 'Расходники и упаковка', unit: 'уп (400 шт)', available_qty: 30, is_stop: false },
        { id: 95, sku: 'SKU-0095', name: 'Размешиватели деревянные березовые 14 см', category: 'Расходники и упаковка', unit: 'уп (1000 шт)', available_qty: 50, is_stop: false },
        { id: 96, sku: 'SKU-0096', name: 'Пакеты крафтовые с кручеными ручками 26х15х34 см', category: 'Расходники и упаковка', unit: 'уп (50 шт)', available_qty: 22, is_stop: false },
        { id: 97, sku: 'SKU-0097', name: 'Пакеты крафтовые без ручек (уголки для выпечки)', category: 'Расходники и упаковка', unit: 'уп (200 шт)', available_qty: 40, is_stop: false },
        { id: 98, sku: 'SKU-0098', name: 'Коробка крафт под сэндвич/бейгл с окошком', category: 'Расходники и упаковка', unit: 'уп (50 шт)', available_qty: 18, is_stop: false },
        { id: 99, sku: 'SKU-0099', name: 'Коробка под десерты 15х15х10 см самосборная', category: 'Расходники и упаковка', unit: 'уп (50 шт)', available_qty: 16, is_stop: false },
        { id: 100, sku: 'SKU-0100', name: 'Вилки одноразовые кукурузный крахмал белые', category: 'Расходники и упаковка', unit: 'уп (100 шт)', available_qty: 25, is_stop: false },
        { id: 101, sku: 'SKU-0101', name: 'Ложки чайные био белые 12 см', category: 'Расходники и упаковка', unit: 'уп (100 шт)', available_qty: 30, is_stop: false },
        { id: 102, sku: 'SKU-0102', name: 'Пергамент силиконизированный в рулоне 38 см х 50 м', category: 'Расходники и упаковка', unit: 'рул', available_qty: 12, is_stop: false },
        { id: 103, sku: 'SKU-0103', name: 'Пленка пищевая полиэтиленовая 30 см х 300 м', category: 'Расходники и упаковка', unit: 'рул', available_qty: 8, is_stop: false },
        { id: 104, sku: 'SKU-0104', name: 'Скотч упаковочный с логотипом сети 48 мм', category: 'Расходники и упаковка', unit: 'рул', available_qty: 0, is_stop: true },
      ]
    },
    {
      category: 'Химия и хозтовары',
      items_count: 14,
      items: [
        { id: 105, sku: 'SKU-0105', name: 'Средство чистки кофемашин от кофейных масел Urnex Cafiza (900 г)', category: 'Химия и хозтовары', unit: 'бан', available_qty: 15, is_stop: false },
        { id: 106, sku: 'SKU-0106', name: 'Жидкость для промывки молочных систем Urnex Rinza (1 л)', category: 'Химия и хозтовары', unit: 'бут', available_qty: 12, is_stop: false },
        { id: 107, sku: 'SKU-0107', name: 'Средство от накипи / декальцинация Urnex Dezcal (1 л)', category: 'Химия и хозтовары', unit: 'бут', available_qty: 9, is_stop: false },
        { id: 108, sku: 'SKU-0108', name: 'Таблетки для очистки жерновов кофемолки Urnex Grindz (430 г)', category: 'Химия и хозтовары', unit: 'бан', available_qty: 0, is_stop: true },
        { id: 109, sku: 'SKU-0109', name: 'Чистящий спрей антижир Азелит Профи (600 мл)', category: 'Химия и хозтовары', unit: 'бут', available_qty: 24, is_stop: false },
        { id: 110, sku: 'SKU-0110', name: 'Гель для мытья посуды Fairy Proline Expert (5 л)', category: 'Химия и хозтовары', unit: 'бут', available_qty: 6, is_stop: false },
        { id: 111, sku: 'SKU-0111', name: 'Перчатки нитриловые черные размер S', category: 'Химия и хозтовары', unit: 'уп (100 шт)', available_qty: 14, is_stop: false },
        { id: 112, sku: 'SKU-0112', name: 'Перчатки нитриловые черные размер M', category: 'Химия и хозтовары', unit: 'уп (100 шт)', available_qty: 20, is_stop: false },
        { id: 113, sku: 'SKU-0113', name: 'Перчатки нитриловые черные размер L', category: 'Химия и хозтовары', unit: 'уп (100 шт)', available_qty: 16, is_stop: false },
        { id: 114, sku: 'SKU-0114', name: 'Чековая лента термо 80х80х12 мм (для фискального регистратора)', category: 'Химия и хозтовары', unit: 'уп (10 рул)', available_qty: 32, is_stop: false },
        { id: 115, sku: 'SKU-0115', name: 'Чековая лента термо 57х40х12 мм (для банковского терминала)', category: 'Химия и хозтовары', unit: 'уп (10 рул)', available_qty: 28, is_stop: false },
        { id: 116, sku: 'SKU-0116', name: 'Мешки для мусора сверхпрочные 120 л черные', category: 'Химия и хозтовары', unit: 'уп (20 шт)', available_qty: 40, is_stop: false },
        { id: 117, sku: 'SKU-0117', name: 'Бумажные полотенца Z-сложение 2-слойные белые', category: 'Химия и хозтовары', unit: 'уп (200 шт)', available_qty: 35, is_stop: false },
        { id: 118, sku: 'SKU-0118', name: 'Щетка угловая со сменной щетиной для чистки группы', category: 'Химия и хозтовары', unit: 'шт', available_qty: 8, is_stop: false },
      ]
    }
  ]
};
